package ratchet

import (
	"sync"
	"time"

	"github.com/go-i2p/crypto/ratchet"
	"github.com/samber/oops"
)

// Session represents an active encrypted session with a remote destination.
// It maintains separate sending and receiving ratchet chains as required by
// the ECIES-X25519-AEAD-Ratchet Double Ratchet protocol.
//
// Thread safety: Session has its own mutex that protects ratchet state during
// crypto operations. The session manager lock and session lock have a defined
// ordering to prevent deadlocks.
type Session struct {
	mu               sync.Mutex
	RemotePublicKey  [32]byte
	DHRatchet        *ratchet.DHRatchet
	SymmetricRatchet *ratchet.SymmetricRatchet // sending chain
	TagRatchet       *ratchet.TagRatchet       // sending tags
	// RecvSymmetricRatchet is the receiving chain ratchet.
	RecvSymmetricRatchet *ratchet.SymmetricRatchet
	// RecvTagRatchet is the receiving tag ratchet.
	RecvTagRatchet *ratchet.TagRatchet
	LastUsed       time.Time
	MessageCounter uint32
	// recvWindowBase is the lowest ES message counter we will still accept.
	// It advances as leading counters are consumed.
	// Spec ref: ratchet.md §"Existing Session" — ≤128-message receive window.
	recvWindowBase uint32
	// recvFillMark is the next counter for which we have NOT yet pre-derived a
	// message key.  Keys for [recvWindowBase, recvFillMark) live in recvKeyCache.
	recvFillMark uint32
	// recvKeyCache maps ES message counter → pre-derived message key.
	// Keys are removed from the cache once consumed; the absence of a counter
	// that is within [recvWindowBase, recvFillMark) means it was already used.
	recvKeyCache map[uint32][32]byte
	// pendingTags tracks tags we expect to receive (tag window).
	pendingTags [][8]byte
	// dhRatchetCounter tracks messages since last DH ratchet rotation.
	dhRatchetCounter uint32
	// consecutiveDHFailures tracks how many DH ratchet steps have failed in a row.
	consecutiveDHFailures uint32
	// newEphemeralPub holds the new ephemeral public key for the peer.
	newEphemeralPub *[32]byte
	// handshakeState retains intermediate Noise IK state for NSR.
	// Non-nil when NSR has not yet been sent (responder) or received (initiator).
	handshakeState *noiseHandshakeState
	// isInitiator tracks whether we initiated the session (sent NS).
	isInitiator bool
	// nsrTag is the NSR tag registered in the SessionManager's nsrTagIndex.
	// Non-nil only on initiator sessions until the NSR has been received.
	// Used to clean up the index entry on session eviction or expiry.
	nsrTag *[8]byte

	// sendKeyID is the current send-direction DH ratchet key ID.
	// Incremented each time we generate a new forward key.
	// Spec ref: ratchet.md §"Key and Tag Set IDs".
	sendKeyID uint16
	// recvKeyID is the current receive-direction DH ratchet key ID.
	// Updated when we receive a NextKey block from the peer.
	recvKeyID uint16
	// pendingNextKeys holds NextKey blocks to include in the next outgoing message.
	// These are generated when the DH ratchet rotates and consumed when sent.
	pendingNextKeys []PayloadBlock
	// awaitingReverseKey tracks whether we sent a forward NextKey with
	// request-reverse set and are waiting for the peer's reverse key.
	awaitingReverseKey bool
	// nextRecvTagCounter is the ES message counter that the NEXT recv tag
	// generated by RecvTagRatchet.GenerateNextTag() corresponds to.
	// Tags and message keys advance in lockstep: tag N decrypts with
	// the message key at counter N. Tracking this lets us store a
	// tag→counter mapping in SessionManager.tagCounterIndex for O(1)
	// AEAD decryption instead of scanning the entire recv window.
	nextRecvTagCounter uint32

	// pendingAcks holds Ack blocks to include in the next outgoing ES message.
	// These are queued when an AckRequest block is received from the peer.
	// Spec ref: ratchet.md §"Ack" and §"Ack Request".
	pendingAcks []PayloadBlock
	// lastAckedEntries records the most recently received Ack entries from the peer.
	// Callers can inspect this to confirm message delivery.
	lastAckedEntries []AckEntry

	// awaitingFirstES is set to true on the responder (Bob) after sending an NSR.
	// The spec (ratchet.md §"Notes" after §1g) states:
	//   "Bob must receive an ES message from Alice before sending ES messages."
	// While this flag is true, encryptExistingSession will reject outbound ES.
	// It is cleared when the first inbound ES message is successfully decrypted.
	awaitingFirstES bool
}

// createSession initializes a new Session with ratchet state from derived keys.
// The isInitiator flag determines key direction: the initiator's send ratchets
// use "initiator" direction keys and its receive ratchets use "responder" direction
// keys (and vice versa for the responder).
func createSession(remotePubKey [32]byte, keys *sessionKeys, ourPrivateKey [32]byte, isInitiator bool) (*Session, error) {
	sendRootKey, recvRootKey, err := deriveDirectionalKeys(keys.rootKey, isInitiator)
	if err != nil {
		return nil, oops.Wrapf(err, "failed to derive directional root keys")
	}
	sendTagKey, recvTagKey, err := deriveDirectionalKeys(keys.tagKey, isInitiator)
	if err != nil {
		return nil, oops.Wrapf(err, "failed to derive directional tag keys")
	}

	dhRatchet := ratchet.NewDHRatchet(keys.rootKey, ourPrivateKey, remotePubKey)
	symRatchet := ratchet.NewSymmetricRatchet(sendRootKey)
	tagRatchet := ratchet.NewTagRatchet(sendTagKey)
	recvSymRatchet := ratchet.NewSymmetricRatchet(recvRootKey)
	recvTagRatchet := ratchet.NewTagRatchet(recvTagKey)

	return &Session{
		RemotePublicKey:      remotePubKey,
		DHRatchet:            dhRatchet,
		SymmetricRatchet:     symRatchet,
		TagRatchet:           tagRatchet,
		RecvSymmetricRatchet: recvSymRatchet,
		RecvTagRatchet:       recvTagRatchet,
		LastUsed:             time.Now(),
		MessageCounter:       1,
		// recvWindowBase starts at 1: message 0 is the NS handshake, not an ES ratchet message.
		// Spec ref: ratchet.md §"Existing Session message" — first ES counter is 1.
		recvWindowBase:     1,
		recvFillMark:       1,
		recvKeyCache:       make(map[uint32][32]byte),
		pendingTags:        make([][8]byte, 0, tagWindowSize),
		pendingNextKeys:    nil,
		nextRecvTagCounter: 1,
	}, nil
}

// GetPendingAcks returns any Ack blocks that should be included in the next
// outgoing Existing Session message. The returned blocks are removed from the
// session's pending queue.
//
// Spec ref: ratchet.md §"Ack" — after receiving an AckRequest block, the
// recipient should include an Ack block in the next outgoing message.
//
// Must be called with session.mu held.
func (s *Session) GetPendingAcks() []PayloadBlock {
	if len(s.pendingAcks) == 0 {
		return nil
	}
	blocks := s.pendingAcks
	s.pendingAcks = nil
	return blocks
}

// GetLastAckedEntries returns the most recently received Ack entries from the
// peer. This allows callers to confirm which messages the peer has received.
//
// Must be called with session.mu held.
func (s *Session) GetLastAckedEntries() []AckEntry {
	return s.lastAckedEntries
}
