package ssu2

import (
	"encoding/binary"
	"net"

	"github.com/samber/oops"
)

// PeerTest block structures and encoding/decoding for SSU2 protocol.
//
// SSU2 peer testing uses a seven-message protocol with message codes 1-7:
// 1. Alice -> Bob: Request (initiator requests test via relay)
// 2. Bob -> Charlie: Relay (relay forwards request to responder)
// 3. Charlie -> Bob: Response (responder acknowledges to relay)
// 4. Bob -> Alice: Result (relay sends result to initiator)
// 5. Charlie -> Alice: Probe (responder probes initiator directly)
// 6. Alice -> Charlie: Reply (initiator confirms probe received)
// 7. Charlie -> Alice: Confirmation (responder confirms successful test)
//
// These blocks use Type 10 (BlockTypePeerTest) with different message codes.
//
// Design rationale:
// - Seven message types encoded via message code field
// - Uses standard library encoding for wire format compatibility
// - Validates all field sizes per SSU2 specification
// - Defensive copies prevent mutation of shared data
// - Error handling provides context for debugging

// PeerTestMessageCode identifies the message type in the seven-message protocol.
type PeerTestMessageCode uint8

const (
	// PeerTestRequest (1): Alice -> Bob, request test via relay
	PeerTestRequest PeerTestMessageCode = 1

	// PeerTestRelay (2): Bob -> Charlie, relay request to responder
	PeerTestRelay PeerTestMessageCode = 2

	// PeerTestResponse (3): Charlie -> Bob, responder acknowledges
	PeerTestResponse PeerTestMessageCode = 3

	// PeerTestResult (4): Bob -> Alice, relay sends result
	PeerTestResult PeerTestMessageCode = 4

	// PeerTestProbe (5): Charlie -> Alice, responder probes directly
	PeerTestProbe PeerTestMessageCode = 5

	// PeerTestReply (6): Alice -> Charlie, initiator confirms probe
	PeerTestReply PeerTestMessageCode = 6

	// PeerTestConfirmation (7): Charlie -> Alice, responder confirms success
	PeerTestConfirmation PeerTestMessageCode = 7
)

// String returns string representation of the message code.
func (c PeerTestMessageCode) String() string {
	switch c {
	case PeerTestRequest:
		return "Request"
	case PeerTestRelay:
		return "Relay"
	case PeerTestResponse:
		return "Response"
	case PeerTestResult:
		return "Result"
	case PeerTestProbe:
		return "Probe"
	case PeerTestReply:
		return "Reply"
	case PeerTestConfirmation:
		return "Confirmation"
	default:
		return "Unknown"
	}
}

// PeerTestBlock represents a peer test message (Type 10, Block 10).
// The structure varies by message code, but all share common fields.
type PeerTestBlock struct {
	// MessageCode identifies which of the 7 messages this is (1 byte)
	MessageCode PeerTestMessageCode

	// Nonce uniquely identifies the test session (4 bytes)
	// Generated by Alice, used by all parties
	Nonce uint32

	// AliceAddress is Alice's (initiator's) UDP address (optional)
	// Present in messages 2, 4, 5
	AliceAddress *net.UDPAddr

	// CharlieAddress is Charlie's (responder's) UDP address (optional)
	// Present in messages 1, 4
	CharlieAddress *net.UDPAddr

	// RouterHash is a 32-byte router identity hash (optional)
	// - Message 1 (Request): Charlie's hash (Alice -> Bob)
	// - Message 2 (Relay): Alice's hash (Bob -> Charlie)
	RouterHash []byte

	// Timestamp is seconds since epoch (4 bytes, optional)
	// Present in messages 2, 5
	Timestamp uint32
}

// EncodePeerTestBlock encodes a PeerTest block to wire format.
//
// Wire format varies by message code:
//
// Message 1 (Request: Alice -> Bob):
//
//	[Code:1][Nonce:4][CharlieRouterHash:32][CharlieAddr:variable]
//
// Message 2 (Relay: Bob -> Charlie):
//
//	[Code:1][Nonce:4][AliceRouterHash:32][AliceAddr:variable][Timestamp:4]
//
// Message 3 (Response: Charlie -> Bob):
//
//	[Code:1][Nonce:4]
//
// Message 4 (Result: Bob -> Alice):
//
//	[Code:1][Nonce:4][CharlieAddr:variable][AliceAddr:variable]
//
// Message 5 (Probe: Charlie -> Alice):
//
//	[Code:1][Nonce:4][AliceAddr:variable][Timestamp:4]
//
// Message 6 (Reply: Alice -> Charlie):
//
//	[Code:1][Nonce:4]
//
// Message 7 (Confirmation: Charlie -> Alice):
//
//	[Code:1][Nonce:4]
//
// Address encoding (when present):
//
//	[Type:1][Port:2][IP:4 or 16]
//	Type: 4 = IPv4, 6 = IPv6
//
// Parameters:
//   - block: PeerTestBlock data to encode
//
// Returns:
//   - *SSU2Block: Encoded block ready for transmission
//   - error: If validation fails
func EncodePeerTestBlock(block *PeerTestBlock) (*SSU2Block, error) {
	if block == nil {
		return nil, oops.Errorf("PeerTestBlock is nil")
	}

	// Validate message code
	if block.MessageCode < 1 || block.MessageCode > 7 {
		return nil, oops.Errorf("invalid message code: %d (must be 1-7)", block.MessageCode)
	}

	// Calculate size and validate fields based on message code
	dataSize := 5 // code(1) + nonce(4)

	switch block.MessageCode {
	case PeerTestRequest: // Message 1
		// Requires CharlieRouterHash and CharlieAddress
		if len(block.RouterHash) != 32 {
			return nil, oops.Errorf("message 1 requires 32-byte RouterHash (Charlie), got %d", len(block.RouterHash))
		}
		if block.CharlieAddress == nil {
			return nil, oops.Errorf("message 1 requires CharlieAddress")
		}
		dataSize += 32 + encodeAddressSize(block.CharlieAddress)

	case PeerTestRelay: // Message 2
		// Requires AliceRouterHash, AliceAddress, Timestamp
		if len(block.RouterHash) != 32 {
			return nil, oops.Errorf("message 2 requires 32-byte RouterHash (Alice), got %d", len(block.RouterHash))
		}
		if block.AliceAddress == nil {
			return nil, oops.Errorf("message 2 requires AliceAddress")
		}
		dataSize += 32 + encodeAddressSize(block.AliceAddress) + 4

	case PeerTestResponse: // Message 3
		// Only code + nonce

	case PeerTestResult: // Message 4
		// Requires CharlieAddress and AliceAddress
		if block.CharlieAddress == nil {
			return nil, oops.Errorf("message 4 requires CharlieAddress")
		}
		if block.AliceAddress == nil {
			return nil, oops.Errorf("message 4 requires AliceAddress")
		}
		dataSize += encodeAddressSize(block.CharlieAddress) + encodeAddressSize(block.AliceAddress)

	case PeerTestProbe: // Message 5
		// Requires AliceAddress and Timestamp
		if block.AliceAddress == nil {
			return nil, oops.Errorf("message 5 requires AliceAddress")
		}
		dataSize += encodeAddressSize(block.AliceAddress) + 4

	case PeerTestReply: // Message 6
		// Only code + nonce

	case PeerTestConfirmation: // Message 7
		// Only code + nonce
	}

	// Allocate buffer
	data := make([]byte, dataSize)

	// Encode common fields
	data[0] = uint8(block.MessageCode)
	binary.BigEndian.PutUint32(data[1:5], block.Nonce)

	// Encode message-specific fields
	offset := 5

	switch block.MessageCode {
	case PeerTestRequest: // Message 1
		copy(data[offset:offset+32], block.RouterHash)
		offset += 32
		offset = encodeAddress(data, offset, block.CharlieAddress)

	case PeerTestRelay: // Message 2
		copy(data[offset:offset+32], block.RouterHash)
		offset += 32
		offset = encodeAddress(data, offset, block.AliceAddress)
		binary.BigEndian.PutUint32(data[offset:offset+4], block.Timestamp)

	case PeerTestResponse: // Message 3
		// No additional fields

	case PeerTestResult: // Message 4
		offset = encodeAddress(data, offset, block.CharlieAddress)
		offset = encodeAddress(data, offset, block.AliceAddress)

	case PeerTestProbe: // Message 5
		offset = encodeAddress(data, offset, block.AliceAddress)
		binary.BigEndian.PutUint32(data[offset:offset+4], block.Timestamp)

	case PeerTestReply: // Message 6
		// No additional fields

	case PeerTestConfirmation: // Message 7
		// No additional fields
	}

	return NewSSU2Block(BlockTypePeerTest, data), nil
}

// DecodePeerTestBlock decodes a PeerTest block from wire format.
//
// Parameters:
//   - ssu2Block: SSU2Block with Type 10
//
// Returns:
//   - *PeerTestBlock: Decoded peer test message
//   - error: If decoding fails or validation fails
func DecodePeerTestBlock(ssu2Block *SSU2Block) (*PeerTestBlock, error) {
	if ssu2Block == nil {
		return nil, oops.Errorf("block is nil")
	}

	if ssu2Block.Type != BlockTypePeerTest {
		return nil, oops.Errorf("invalid block type: expected %d, got %d", BlockTypePeerTest, ssu2Block.Type)
	}

	data := ssu2Block.Data
	if len(data) < 5 {
		return nil, oops.Errorf("PeerTest block too short: %d bytes (minimum 5)", len(data))
	}

	// Decode common fields
	block := &PeerTestBlock{
		MessageCode: PeerTestMessageCode(data[0]),
		Nonce:       binary.BigEndian.Uint32(data[1:5]),
	}

	// Validate message code
	if block.MessageCode < 1 || block.MessageCode > 7 {
		return nil, oops.Errorf("invalid message code: %d (must be 1-7)", block.MessageCode)
	}

	offset := 5

	// Decode message-specific fields
	switch block.MessageCode {
	case PeerTestRequest: // Message 1: [Code][Nonce][CharlieHash][CharlieAddr]
		if len(data) < offset+32 {
			return nil, oops.Errorf("message 1 too short for RouterHash: %d bytes", len(data))
		}
		block.RouterHash = make([]byte, 32)
		copy(block.RouterHash, data[offset:offset+32])
		offset += 32

		addr, n, err := decodeAddress(data, offset)
		if err != nil {
			return nil, oops.Wrapf(err, "failed to decode CharlieAddress")
		}
		block.CharlieAddress = addr
		offset += n

	case PeerTestRelay: // Message 2: [Code][Nonce][AliceHash][AliceAddr][Timestamp]
		if len(data) < offset+32 {
			return nil, oops.Errorf("message 2 too short for RouterHash: %d bytes", len(data))
		}
		block.RouterHash = make([]byte, 32)
		copy(block.RouterHash, data[offset:offset+32])
		offset += 32

		addr, n, err := decodeAddress(data, offset)
		if err != nil {
			return nil, oops.Wrapf(err, "failed to decode AliceAddress")
		}
		block.AliceAddress = addr
		offset += n

		if len(data) < offset+4 {
			return nil, oops.Errorf("message 2 too short for Timestamp: %d bytes", len(data))
		}
		block.Timestamp = binary.BigEndian.Uint32(data[offset : offset+4])

	case PeerTestResponse: // Message 3: [Code][Nonce]
		// No additional fields

	case PeerTestResult: // Message 4: [Code][Nonce][CharlieAddr][AliceAddr]
		addr, n, err := decodeAddress(data, offset)
		if err != nil {
			return nil, oops.Wrapf(err, "failed to decode CharlieAddress")
		}
		block.CharlieAddress = addr
		offset += n

		addr2, n2, err := decodeAddress(data, offset)
		if err != nil {
			return nil, oops.Wrapf(err, "failed to decode AliceAddress")
		}
		block.AliceAddress = addr2
		offset += n2

	case PeerTestProbe: // Message 5: [Code][Nonce][AliceAddr][Timestamp]
		addr, n, err := decodeAddress(data, offset)
		if err != nil {
			return nil, oops.Wrapf(err, "failed to decode AliceAddress")
		}
		block.AliceAddress = addr
		offset += n

		if len(data) < offset+4 {
			return nil, oops.Errorf("message 5 too short for Timestamp: %d bytes", len(data))
		}
		block.Timestamp = binary.BigEndian.Uint32(data[offset : offset+4])

	case PeerTestReply: // Message 6: [Code][Nonce]
		// No additional fields

	case PeerTestConfirmation: // Message 7: [Code][Nonce]
		// No additional fields
	}

	return block, nil
}

// encodeAddressSize calculates the encoded size of a UDP address.
// Format: [Type:1][Port:2][IP:4 or 16]
func encodeAddressSize(addr *net.UDPAddr) int {
	if addr == nil {
		return 0
	}
	if addr.IP.To4() != nil {
		return 1 + 2 + 4 // type + port + ipv4
	}
	return 1 + 2 + 16 // type + port + ipv6
}

// encodeAddress encodes a UDP address into the buffer at the given offset.
// Format: [Type:1][Port:2][IP:4 or 16]
// Type: 4 = IPv4, 6 = IPv6
// Returns the new offset after encoding.
func encodeAddress(data []byte, offset int, addr *net.UDPAddr) int {
	if addr == nil {
		return offset
	}

	if ipv4 := addr.IP.To4(); ipv4 != nil {
		data[offset] = 4 // IPv4
		binary.BigEndian.PutUint16(data[offset+1:offset+3], uint16(addr.Port))
		copy(data[offset+3:offset+7], ipv4)
		return offset + 7
	}

	// IPv6
	data[offset] = 6 // IPv6
	binary.BigEndian.PutUint16(data[offset+1:offset+3], uint16(addr.Port))
	copy(data[offset+3:offset+19], addr.IP.To16())
	return offset + 19
}

// decodeAddress decodes a UDP address from the buffer at the given offset.
// Format: [Type:1][Port:2][IP:4 or 16]
// Returns the decoded address, bytes consumed, and any error.
func decodeAddress(data []byte, offset int) (*net.UDPAddr, int, error) {
	if len(data) < offset+1 {
		return nil, 0, oops.Errorf("insufficient data for address type")
	}

	addrType := data[offset]
	if addrType == 4 {
		// IPv4
		if len(data) < offset+7 {
			return nil, 0, oops.Errorf("insufficient data for IPv4 address: need 7 bytes, have %d", len(data)-offset)
		}
		port := binary.BigEndian.Uint16(data[offset+1 : offset+3])
		ip := make(net.IP, 4)
		copy(ip, data[offset+3:offset+7])
		return &net.UDPAddr{IP: ip, Port: int(port)}, 7, nil
	}

	if addrType == 6 {
		// IPv6
		if len(data) < offset+19 {
			return nil, 0, oops.Errorf("insufficient data for IPv6 address: need 19 bytes, have %d", len(data)-offset)
		}
		port := binary.BigEndian.Uint16(data[offset+1 : offset+3])
		ip := make(net.IP, 16)
		copy(ip, data[offset+3:offset+19])
		return &net.UDPAddr{IP: ip, Port: int(port)}, 19, nil
	}

	return nil, 0, oops.Errorf("invalid address type: %d (expected 4 or 6)", addrType)
}
